esp8266:
  board: nodemcuv2
  framework:
    version: recommended
    
sensor:
  - platform: aht10
    variant: AHT10
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s